Repository clue/reactphp-docker, pull requests merged in 2020-02, with the labels that each got.

#57 Add network api
  src/Client.php
  tests/ClientTest.php
  tests/FunctionalClientTest.php
Labels: new feature

#58 Add support / sponsorship info
  .github/FUNDING.yml
Labels: maintenance

#59 Test against PHP 7.4 and simplify test matrix
  .travis.yml
Labels: easy pick, maintenance
